// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwbmncsjuneaxvpstarv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3Ym1uY3NqdW5lYXh2cHN0YXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTMwODMsImV4cCI6MjA2NDA4OTA4M30.Mo9zWLNXKeGPQbMYK_UQkMeNKb_RRx7KZMbNlXONsf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);